id: P007942
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:50:40.493525
source_metadata:
  id: bdr:W2PD17445
  title: སྤྱིར་བཏང་དངོས་ལུགས་དངོས་བཤེར། ཤུགས་རིག་པ། ཚ་བ་རིག་པ།
  author: ''
  volumes:
    b4d1f7626aab4d75b8507e4e3ed4a5d0:
      image_group_id: I2PD17961
      title: Volume 1 of spyir btang dngos lugs dngos bsher/ shugs rig pa/ tsha ba
        rig pa/
      volume_number: 1
      total_pages: 254
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
