id: P007942
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17445
  title: སྤྱིར་བཏང་དངོས་ལུགས་དངོས་བཤེར། ཤུགས་རིག་པ། ཚ་བ་རིག་པ།
  author: ''
  volumes:
    db17ffa0601647249f0483d197044bf9:
      image_group_id: I2PD17961
      title: ''
      volume_number: 1
      total_pages: 254
ebook_metadata:
  title: སྤྱིར་བཏང་དངོས་ལུགས་དངོས་བཤེར། ཤུགས་རིག་པ། ཚ་བ་རིག་པ།
  author: ''
  sku: P007942
  cover: cover.jpg
  layers:
  - pagination
